-- ******************** SqlDBM: Microsoft SQL Server ********************
-- ************************* Generated by SqlDBM ************************


CREATE SEQUENCE Sequence_1 START WITH 1 INCREMENT BY 1;