-- ******************************** SqlDBM: Oracle ********************************
-- * Generated by SqlDBM: Oracle SampleDb, v1 by alexey.alferov+oracle@sqldbm.com *


CREATE SEQUENCE Sequence_1 START WITH 1 INCREMENT BY 1;
-- ************************************** dbo.Supplier
CREATE TABLE dbo.Supplier
(
 SupplierId    NUMBER NOT NULL,
 CompanyName   CHAR(10) NOT NULL,
 Phone         CHAR(10) NOT NULL,
 CONSTRAINT PK_Supplier PRIMARY KEY (SupplierId),
 CONSTRAINT AK1_Supplier_CompanyName UNIQUE (CompanyName)
);
COMMENT ON TABLE dbo.Supplier IS 'Basic information 
about Supplier';

-- ************************************** dbo.Customer
CREATE TABLE dbo.Customer
(
 CustomerId     NUMBER NOT NULL,
 CustomerName   CHAR(40) NOT NULL,
 Phone          CHAR(40) NOT NULL,
 CONSTRAINT PK_Customer PRIMARY KEY (CustomerId),
 CONSTRAINT AK1_Customer_CustomerName UNIQUE (CustomerName)
);
COMMENT ON TABLE dbo.Customer IS 'Basic information 
about Customer';

-- ************************************** dbo.Product
CREATE TABLE dbo.Product
(
 ProductId        NUMBER NOT NULL,
 SupplierId       NUMBER NOT NULL,
 UnitPrice        NUMBER NULL,
 IsDiscontinued   FLOAT DEFAULT 0 NOT NULL,
 CONSTRAINT PK_Product PRIMARY KEY (ProductId),
 CONSTRAINT AK1_Product_SupplierId_ProductName UNIQUE (SupplierId),
 CONSTRAINT FK_Product_SupplierId_Supplier FOREIGN KEY (SupplierId) REFERENCES dbo.Supplier (SupplierId)
);
COMMENT ON TABLE dbo.Product IS 'Basic information 
about Product';

-- ************************************** dbo."Order"
CREATE TABLE dbo."Order"
(
 OrderId       NUMBER NOT NULL,
 OrderNumber   CHAR(10) NULL,
 CustomerId    NUMBER NOT NULL,
 OrderDate     DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
 TotalAmount   NUMBER NOT NULL,
 CONSTRAINT PK_Order PRIMARY KEY (OrderId),
 CONSTRAINT AK1_Order_OrderNumber UNIQUE (OrderNumber),
 CONSTRAINT FK_Order_CustomerId_Customer FOREIGN KEY (CustomerId) REFERENCES dbo.Customer (CustomerId)
);
COMMENT ON TABLE dbo."Order" IS 'Order information
like Date, Amount';

-- ************************************** dbo.OrderItem
CREATE TABLE dbo.OrderItem
(
 OrderId     NUMBER NOT NULL,
 ProductId   NUMBER NOT NULL,
 UnitPrice   NUMBER NOT NULL,
 Quantity    NUMBER NOT NULL,
 CONSTRAINT PK_OrderItem PRIMARY KEY (OrderId, ProductId),
 CONSTRAINT FK_OrderItem_OrderId_Order FOREIGN KEY (OrderId) REFERENCES dbo."Order" (OrderId),
 CONSTRAINT FK_OrderItem_ProductId_Product FOREIGN KEY (ProductId) REFERENCES dbo.Product (ProductId)
);
COMMENT ON TABLE dbo.OrderItem IS 'Information about
like Price, Quantity';

